import { makeStyles } from 'tss-react/mui';

const useStyles = makeStyles()(() => ({
  root: {
    width: 350,
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    background: '#fff',
    borderRadius: 16,
    padding: 32,
    boxShadow: '0 4px 32px rgba(25, 118, 210, 0.10), 0 1.5px 8px rgba(0,0,0,0.08)',
    alignItems: 'center',
  },
  headerRow: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    position: 'relative',
    minHeight: 48,
  },
  title: {
    flex: 1,
    textAlign: 'center',
    fontSize: 28,
    fontWeight: 700,
    color: '#1976d2',
    letterSpacing: 1,
    background: 'linear-gradient(90deg, #1976d2 0%, #42a5f5 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    lineHeight: 1.2,
    borderRadius: 8,
    padding: '4px 0',
    boxShadow: '0 2px 8px rgba(25, 118, 210, 0.07)',
  },
  closeLink: {
    position: 'absolute',
    left: 0,
    color: '#1976d2',
    cursor: 'pointer',
    textDecoration: 'underline',
    fontSize: 16,
    marginLeft: 8,
    top: '50%',
    transform: 'translateY(-50%)',
  },
  centerFields: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 16,
    width: '100%',
  },
  switchAuthRow: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    margin: '8px 0',
  },
  switchAuthLink: {
    color: '#1976d2',
    cursor: 'pointer',
    textDecoration: 'underline',
    fontWeight: 500,
  },
  button: {
    width: '100%',
    marginTop: 8,
    fontWeight: 600,
    fontSize: 18,
    letterSpacing: 0.5,
  },
  requiredStar: {
    color: '#d32f2f',
    marginRight: 2,
    marginLeft: 2,
    fontWeight: 700,
    fontSize: 18,
    verticalAlign: 'middle',
  },
}));

export default useStyles;
